### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by DanielHofer001** [htl-perg-2019-20-5ahif/docker-wpf-exercise-DanielHofer001#1]
https://hub.docker.com/repository/docker/hoferdaniel/bookapi

**Comment by rstropek** [comment]
Well done 👍, you have nearly earned the extra points. See homework spec: "*Note* that the Docker Hub page *must* container a basic description about how to use the Docker image".

**Comment by DanielHofer001** [comment]
Thank you, I added a readme 😃

**Comment by rstropek** [comment]
Docs are important 😉
